[variables]
NIXPACKS_METADATA = "dotnet"

[phases.build]
cmds = [
  "dotnet restore TheGameVoice.sln",
  "dotnet publish src/Web/TheGameVoice.Web/TheGameVoice.Web.csproj -c Release -o /app/publish"
]

[start]
cmd = "dotnet /app/publish/TheGameVoice.Web.dll"