<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Persistence\Repositories\ArticleDetailsViewModel.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="EFCore.NamingConventions" Version="8.0.3" />
    <PackageReference Include="MailKit" Version="4.17.0" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="8.0.27" />

    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.27" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.27">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="8.0.27" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="8.0.11" />
    <PackageReference Include="Serilog" Version="4.3.1" />
    <PackageReference Include="StackExchange.Redis" Version="2.13.1" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Caching\" />
    <Folder Include="DependencyInjection\" />
    <Folder Include="Identity\Configurations\" />
    <Folder Include="Identity\Services\" />
    <Folder Include="Migrations\" />
    <Folder Include="Persistence\Interceptors\" />
    <Folder Include="Storage\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Application\TheGameVoice.Application\TheGameVoice.Application.csproj" />
    <ProjectReference Include="..\..\Domain\TheGameVoice.Domain\TheGameVoice.Domain.csproj" />
    <ProjectReference Include="..\..\Web\TheGameVoice.API\TheGameVoice.API.csproj" />
  </ItemGroup>

</Project>
